main: 'io.arct.testplugin.TestPlugin'
name: 'TestPlugin'
version: '1.0.0'

commands:
  testitems:
    description: Test out all the items.
    aliases: [ti]
  testmessage:
    description: Test message.
    aliases: [tm]
  testcooldown1:
    description: Test cooldown 1.
    aliases: [tc1]
  testcooldown2:
    description: Test cooldown 2.
    aliases: [tc2]